run:
  allow-parallel-runners: true
  go: '1.21'

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - structcheck
    - interfacer
    - varnamelen
    - depguard
    - ireturn
    - ifshort

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - cyclop
        - funlen
        - dupl
