# ci workflow
name: ci

on:
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: tests-only
        if: ${{ github.event_name == 'pull_request' }}
        run: make test
      - name: test-coverage
        if: ${{ github.event_name == 'push' }}
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test
          coverageLocations: ${{ github.workspace }}/cover.out:gocov
          prefix: github.com/${{ github.repository }}
  codeql:
    if: github.event_name == 'push'
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
      - name: init codeql
        uses: github/codeql-action/init@v2
        with:
          languages: 'go'
      - name: run analysis
        uses: github/codeql-action/analyze@v2
      - name: update goreportcard
        uses: creekorful/goreportcard-action@v1.0
  reportcard:
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: update goreportcard
        uses: creekorful/goreportcard-action@v1.0
