# ci workflow
name: ci
Ж:Ж
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
  test:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: run-test
        run: make test
      - name: push-coverage
        if: ${{ github.event_name == 'push' }}
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ github.workspace }}/cover.out
  codeql:
    if: github.event_name == 'push'
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: init codeql
        uses: github/codeql-action/init@v3
        with:
          languages: 'go'
      - name: run analysis
        uses: github/codeql-action/analyze@v3
  reportcard:
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: update goreportcard
        uses: creekorful/goreportcard-action@v1.0
